/bebop104/mocap_filters:
  ros__parameters:
    frequency: 100.0
    
    frames:
      parent: "world"
      child: "bebop104/base_link"
    
    topics:
      # Absolute path to mocap data
      input_pose: "/vrpn_mocap/bebop104/pose"

    levant:
      C: 2.0

    kalman:
      Q_pos: 0.000001
      Q_vel: 0.5

    rho:
      k1: 20.0
      k2: 20.0
      k3: 6.0
      alpha: 0.25