mocap_filters_node:
  ros__parameters:
    frames:
      parent: "world"
      child: "drone_body"
    topics:
      input_pose: "/vrpn_client_node/drone/pose"
    frequency: 100.0

    levant:
      C: 5.0

    rho:
      alpha: 0.25
      k1: 1.5
      k2: 1.5
      k3: 1.0

    kalman:
      # Tuning: Low Q_vel to smooth ripples, Low Q_pos to trust model integration
      # The R (Measurement Noise) is hardcoded low (1e-5) in cpp to trust MoCap position
      Q_pos: 0.0001
      Q_vel: 0.0001

    baseline:
      dirty_N: 20.0 # Cutoff frequency (rad/s)