mocap_filters_node:
  ros__parameters:
    frames:
      parent: "world"
      child: "body_fixed"
    topics:
      input_pose: "/vrpn_mocap/bebop104/pose"
    frequency: 100.0

    levant:
      C: 5.0

    rho:
      alpha: 0.25
      k1: 1.5
      k2: 1.5
      k3: 1.0

    kalman:
      Q_pos: 0.0001
      Q_vel: 0.1

    baseline:
      dirty_N: 20.0